[tool.poetry]
name = "joopney"
version = "0.1.0"
description = ""
authors = ["marcsmerlin <marc.s.merlin@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
jeepney = "^0.8.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
